### PR TITLE
introduce init parameter to set map options

### PR DESCRIPTION
**Pull request by thet**
Introduce a ``mapoptions`` parameter to set the options of the minimap map.
This fixes a problem, where the minimap was also using the Leaflet.Sleep Plugin
(https://github.com/CliffCloud/Leaflet.Sleep). Now you can explicitly set and
override the options for the minimap map. In this case by setting ``sleep:
false`` like so:

```
var minimap = new L.Control.MiniMap(
    L.tileLayer.provider("OpenStreetMap.Mapnik"),
    {},
    {sleep: false}
).addTo(map);
```

### CODE REVIEW

**Comment by thet** [comment]
Done!

**Comment by thet** [comment]
By the way, there is a test script, but where are the tests defined? Cant find them anywhere.

**Comment by robpvn** [comment]
There aren't any tests, I'm afraid! :scream:  The test command just runs a code linter that enforces the coding style we've used. 

Nice work on the map options!

**Comment by thet** [comment]
NP for tests - saves some work for me, at least now :)
Thanks merging and this nice plugin!

**Pull request merged**
