### PR TITLE
[BREAKING CHANGE] Pass translation strings as options

### LINKED ISSUE #89: Translation strings
Is there a performance reason for not being able to set `hideText`/`showText` as options rather than having to override them in a subclass?

Asking since i18n by passing-as-an-option seems to be standard among the Leaflet controls I've encountered.

### PR DESCRIPTION
**Pull request by lokal-profil**
Replaces the existing subclass method.

Fixes #89

### CODE REVIEW

**Comment by robpvn** [comment]
Looking it this, I realised that we can make the change "less breaking", if we leave in the -de.js translation file and just rename hideText to options.hideText in that file. That would work, wouldn't it? 

Ideally I'd still like to go the Leaflet.i18n route because it's nice to be cooperative with other plugins, but I realise it's a bit silly to bring in a whole dependency for just two strings.

**Comment by lokal-profil** [comment]
options.hideText in the ...-de.js file didn't work when I tried that (gives syntax error). Similarly setting
```
options: {
    hideText: ...
```
Would override the defaults thus requiring all of the default options to be present in the ...-de.js file.

**Comment by robpvn** [comment]
What if we move the strings into a sub-object, e.g. `options.strings.hideText` - That would also make a cleaner options object, especially if we ever need new strings.

**Comment by lokal-profil** [comment]
I like the idea of a sub-object. 

Don't think it helps with the ...-de.js file though. The only way I can see how the sub-classing can be kept in parallel to i18n-via-options is if it sets some override object and there is a call during initialization to override strings if that object is present. To me that sounds less clean than a breaking change.

**Comment by robpvn** [comment]
Yes, I agree. Translation strings as a options sub-object are the way to go. Will you make it happen? :+1:

**Comment by lokal-profil** [comment]
Done =)

**Comment by robpvn** [comment]
Looking good! We just need to mention the sub-object options in the README and we should be good to go.

**Comment by lokal-profil** [comment]
Argh, forgot to update the readme. Will do that and add an example file with the german translations

**Comment by robpvn** [comment]
Brilliant, thanks for the work!

**Pull request merged**
