### PR TITLE
Removed leaflet dependency, rebuilt dist files

### PR DESCRIPTION
**Pull request by w8r**
Moved `leaflet` to dev dependencies, for 2 reasons:

 * it breaks all the dependencies in case you are trying to use it along with `leaflet@1.x`
 * it's not actually a dependency, it's compatibility, and it's not correct in this case, I use it with `leaflet@1.x`

Thank you very much for the plugin!

### CODE REVIEW

**Comment by robpvn** [comment]
Sounds good, guess this cloes issue #116. Sorry I've been unresponsive!

**Comment by sroucheray** [comment]
Hi @robpvn, can you merge this PR. I need it for a project :)
Thanks !

**Comment by robpvn** [comment]
OMG, I forgot to actually merge this when I wrote the approving comment. Sorry!

**Comment by w8r** [comment]
thanks!

**Comment by sroucheray** [comment]
Thank you !

**Pull request merged**
