### PR TITLE
Added support for CommonJS

### PR DESCRIPTION
**Pull request by kuuup**

### CODE REVIEW

**Comment by robpvn** [comment]
I'm not well versed in CommonJS, how does this work someplace without a require function (aka. in a web browser where Leaflet has already been loaded into L?)

**Comment by kuuup** [comment]
You can use it without L.

var MiniMap = require('leaflet-minimap');
(or import MiniMap from 'leaflet-minimap'; in ES6)
...
 MiniMap(layer, options).addTo(map)

**Comment by robpvn** [comment]
I checked out the branch and tried opening example/example.html, and it didn't work because the browser doesn't have a require function, like I was afraid of. Any way you can make this work without breaking compatibility with existing use of the plugin?

**Comment by kuuup** [comment]
You're right, I missed that! 

I made a new commit to avoid this problem.
Please try my changes in your environment.

**Comment by robpvn** [comment]
Well, this seems to work and be safe for existing users! Would you mind adding a bit about it in the README so future users can discover it more easily?

**Comment by kuuup** [comment]
I've changed the README a week ago. Is there something else that holds you back from merging?

**Comment by robpvn** [comment]
Sorry, looks like I never got an alert from GitHub that something had changed. (Or it drowned somewhere in my inbox...) Looks great, thanks for your contribution!

**Pull request merged**
